export const FETCH_ANALYSIS_REQUEST = "FETCH_ANALYSIS_REQUEST";
export const FETCH_ANALYSIS_SUCCESS = "FETCH_ANALYSIS_SUCCESS";
export const FETCH_ANALYSIS_FAIL = "FETCH_ANALYSIS_FAIL";

export const ANALYSIS_DETAIL_REQUEST = "ANALYSIS_DETAIL_REQUEST";
export const ANALYSIS_DETAIL_SUCCESS = "ANALYSIS_DETAIL_SUCCESS";
export const ANALYSIS_DETAIL_FAIL = "ANALYSIS_DETAIL_FAIL";

