export const FETCH_ASSERTS_REQUEST = "FETCH_ASSERTS_REQUEST";
export const FETCH_ASSERTS_SUCCESS = "FETCH_ASSERTS_SUCCESS";
export const FETCH_ASSERTS_FAIL = "FETCH_ASSERTS_FAIL";

export const ASSERT_DETAIL_REQUEST = "ASSERT_DETAIL_REQUEST";
export const ASSERT_DETAIL_SUCCESS = "ASSERT_DETAIL_SUCCESS";
export const ASSERT_DETAIL_FAIL = "ASSERT_DETAIL_FAIL";

export const CREATE_ASSERT_REQUEST = "CREATE_ASSERT_REQUEST";
export const CREATE_ASSERT_SUCCESS = "CREATE_ASSERT_SUCCESS";
export const CREATE_ASSERT_FAIL = "CREATE_ASSERT_FAIL";

export const UPDATE_ASSERT_REQUEST = "UPDATE_ASSERT_REQUEST";
export const UPDATE_ASSERT_SUCCESS = "UPDATE_ASSERT_SUCCESS";
export const UPDATE_ASSERT_FAIL = "UPDATE_ASSERT_FAIL";

export const DELETE_ASSERT_REQUEST = "DELETE_ASSERT_REQUEST";
export const DELETE_ASSERT_SUCCESS = "DELETE_ASSERT_SUCCESS";
export const DELETE_ASSERT_FAIL = "DELETE_ASSERT_FAIL";