export const FETCH_BANK_ACCOUNTS_REQUEST = "FETCH_BANK_ACCOUNTS_REQUEST";
export const FETCH_BANK_ACCOUNTS_SUCCESS = "FETCH_BANK_ACCOUNTS_SUCCESS";
export const FETCH_BANK_ACCOUNTS_FAIL = "FETCH_BANK_ACCOUNTS_FAIL";

export const FETCH_BANK_ACCOUNTS_DROPDOWN_REQUEST = "FETCH_BANK_ACCOUNTS_DROPDOWN_REQUEST";
export const FETCH_BANK_ACCOUNTS_DROPDOWN_SUCCESS = "FETCH_BANK_ACCOUNTS_DROPDOWN_SUCCESS";
export const FETCH_BANK_ACCOUNTS_DROPDOWN_FAIL = "FETCH_BANK_ACCOUNTS_DROPDOWN_FAIL";

export const CREATE_BANK_ACCOUNT_REQUEST = "CREATE_BANK_ACCOUNT_REQUEST";
export const CREATE_BANK_ACCOUNT_SUCCESS = "CREATE_BANK_ACCOUNT_SUCCESS";
export const CREATE_BANK_ACCOUNT_FAIL = "CREATE_BANK_ACCOUNT_FAIL";

export const UPDATE_BANK_ACCOUNT_REQUEST = "UPDATE_BANK_ACCOUNT_REQUEST";
export const UPDATE_BANK_ACCOUNT_SUCCESS = "UPDATE_BANK_ACCOUNT_SUCCESS";
export const UPDATE_BANK_ACCOUNT_FAIL = "UPDATE_BANK_ACCOUNT_FAIL";

export const BANK_ACCOUNT_DETAIL_REQUEST = "BANK_ACCOUNT_DETAIL_REQUEST";
export const BANK_ACCOUNT_DETAIL_SUCCESS = "BANK_ACCOUNT_DETAIL_SUCCESS";
export const BANK_ACCOUNT_DETAIL_FAIL = "BANK_ACCOUNT_DETAIL_FAIL";

export const BANK_ACCOUNT_PRODUCT_REQUEST = "BANK_ACCOUNT_PRODUCT_REQUEST";
export const BANK_ACCOUNT_PRODUCT_SUCCESS = "BANK_ACCOUNT_PRODUCT_SUCCESS";
export const BANK_ACCOUNT_PRODUCT_FAIL = "BANK_ACCOUNT_PRODUCT_FAIL";

export const DELETE_BANK_ACCOUNT_REQUEST = "DELETE_BANK_ACCOUNT_REQUEST";
export const DELETE_BANK_ACCOUNT_SUCCESS = "DELETE_BANK_ACCOUNT_SUCCESS";
export const DELETE_BANK_ACCOUNT_FAIL = "DELETE_BANK_ACCOUNT_FAIL";