export const FETCH_BRANCHES_REQUEST = "FETCH_BRANCHES_REQUEST";
export const FETCH_BRANCHES_SUCCESS = "FETCH_BRANCHES_SUCCESS";
export const FETCH_BRANCHES_FAIL = "FETCH_BRANCHES_FAIL";

export const FETCH_BRANCHES_DROPDOWN_REQUEST = "FETCH_BRANCHES_DROPDOWN_REQUEST";
export const FETCH_BRANCHES_DROPDOWN_SUCCESS = "FETCH_BRANCHES_DROPDOWN_SUCCESS";
export const FETCH_BRANCHES_DROPDOWN_FAIL = "FETCH_BRANCHES_DROPDOWN_FAIL";

export const CREATE_BRANCH_REQUEST = "CREATE_BRANCH_REQUEST";
export const CREATE_BRANCH_SUCCESS = "CREATE_BRANCH_SUCCESS";
export const CREATE_BRANCH_FAIL = "CREATE_BRANCH_FAIL";

export const UPDATE_BRANCH_REQUEST = "UPDATE_BRANCH_REQUEST";
export const UPDATE_BRANCH_SUCCESS = "UPDATE_BRANCH_SUCCESS";
export const UPDATE_BRANCH_FAIL = "UPDATE_BRANCH_FAIL";

export const BRANCH_DETAIL_REQUEST = "BRANCH_DETAIL_REQUEST";
export const BRANCH_DETAIL_SUCCESS = "BRANCH_DETAIL_SUCCESS";
export const BRANCH_DETAIL_FAIL = "BRANCH_DETAIL_FAIL";

export const BRANCH_PRODUCT_REQUEST = "BRANCH_PRODUCT_REQUEST";
export const BRANCH_PRODUCT_SUCCESS = "BRANCH_PRODUCT_SUCCESS";
export const BRANCH_PRODUCT_FAIL = "BRANCH_PRODUCT_FAIL";

export const DELETE_BRANCH_REQUEST = "DELETE_BRANCH_REQUEST";
export const DELETE_BRANCH_SUCCESS = "DELETE_BRANCH_SUCCESS";
export const DELETE_BRANCH_FAIL = "DELETE_BRANCH_FAIL";