export const FETCH_CLIENTS_REQUEST = "FETCH_CLIENTS_REQUEST";
export const FETCH_CLIENTS_SUCCESS = "FETCH_CLIENTS_SUCCESS";
export const FETCH_CLIENTS_FAIL = "FETCH_CLIENTS_FAIL";

export const FETCH_CLIENTS_DROPDOWN_REQUEST = "FETCH_CLIENTS_DROPDOWN_REQUEST";
export const FETCH_CLIENTS_DROPDOWN_SUCCESS = "FETCH_CLIENTS_DROPDOWN_SUCCESS";
export const FETCH_CLIENTS_DROPDOWN_FAIL = "FETCH_CLIENTS_DROPDOWN_FAIL";

export const CLIENT_DETAIL_REQUEST = "CLIENT_DETAIL_REQUEST";
export const CLIENT_DETAIL_SUCCESS = "CLIENT_DETAIL_SUCCESS";
export const CLIENT_DETAIL_FAIL = "CLIENT_DETAIL_FAIL";

export const CREATE_CLIENT_REQUEST = "CREATE_CLIENT_REQUEST";
export const CREATE_CLIENT_SUCCESS = "CREATE_CLIENT_SUCCESS";
export const CREATE_CLIENT_FAIL = "CREATE_CLIENT_FAIL";

export const UPDATE_CLIENT_REQUEST = "UPDATE_CLIENT_REQUEST";
export const UPDATE_CLIENT_SUCCESS = "UPDATE_CLIENT_SUCCESS";
export const UPDATE_CLIENT_FAIL = "UPDATE_CLIENT_FAIL";

export const DELETE_CLIENT_REQUEST = "DELETE_CLIENT_REQUEST";
export const DELETE_CLIENT_SUCCESS = "DELETE_CLIENT_SUCCESS";
export const DELETE_CLIENT_FAIL = "DELETE_CLIENT_FAIL";