export const CREATE_CEO_DASHBOARD_REQUEST = "CREATE_CEO_DASHBOARD_REQUEST";
export const CREATE_CEO_DASHBOARD_SUCCESS = "CREATE_CEO_DASHBOARD_SUCCESS";
export const CREATE_CEO_DASHBOARD_FAIL = "CREATE_CEO_DASHBOARD_FAIL";

export const CREATE_HR_DASHBOARD_REQUEST = "CREATE_HR_DASHBOARD_REQUEST";
export const CREATE_HR_DASHBOARD_SUCCESS = "CREATE_HR_DASHBOARD_SUCCESS";
export const CREATE_HR_DASHBOARD_FAIL = "CREATE_HR_DASHBOARD_FAIL";

export const CREATE_BRANCH_MANAGER_DASHBOARD_REQUEST = "CREATE_BRANCH_MANAGER_DASHBOARD_REQUEST";
export const CREATE_BRANCH_MANAGER_DASHBOARD_SUCCESS = "CREATE_BRANCH_MANAGER_DASHBOARD_SUCCESS";
export const CREATE_BRANCH_MANAGER_DASHBOARD_FAIL = "CREATE_BRANCH_MANAGER_DASHBOARD_FAIL";

export const CREATE_TECHNICIAN_DASHBOARD_REQUEST = "CREATE_TECHNICIAN_DASHBOARD_REQUEST";
export const CREATE_TECHNICIAN_DASHBOARD_SUCCESS = "CREATE_TECHNICIAN_DASHBOARD_SUCCESS";
export const CREATE_TECHNICIAN_DASHBOARD_FAIL = "CREATE_TECHNICIAN_DASHBOARD_FAIL";

export const CREATE_SUBDEALER_STAFF_DASHBOARD_REQUEST = "CREATE_SUBDEALER_STAFF_DASHBOARD_REQUEST";
export const CREATE_SUBDEALER_STAFF_DASHBOARD_SUCCESS = "CREATE_SUBDEALER_STAFF_DASHBOARD_SUCCESS";
export const CREATE_SUBDEALER_STAFF_DASHBOARD_FAIL = "CREATE_SUBDEALER_STAFF_DASHBOARD_FAIL";

export const CREATE_SALES_MEN_DASHBOARD_REQUEST = "CREATE_SALES_MEN_DASHBOARD_REQUEST";
export const CREATE_SALES_MEN_DASHBOARD_SUCCESS = "CREATE_SALES_MEN_DASHBOARD_SUCCESS";
export const CREATE_SALES_MEN_DASHBOARD_FAIL = "CREATE_SALES_MEN_DASHBOARD_FAIL";

export const DASHBOARD_DETAIL_REQUEST = "DASHBOARD_DETAIL_REQUEST";
export const DASHBOARD_DETAIL_SUCCESS = "DASHBOARD_DETAIL_SUCCESS";
export const DASHBOARD_DETAIL_FAIL = "DASHBOARD_DETAIL_FAIL";
 
export const CREATE_WAREHOUSE_MANAGER_DASHBOARD_REQUEST = "CREATE_WAREHOUSE_MANAGER_DASHBOARD_REQUEST";
export const CREATE_WAREHOUSE_MANAGER_DASHBOARD_SUCCESS = "CREATE_WAREHOUSE_MANAGER_DASHBOARD_SUCCESS";
export const CREATE_WAREHOUSE_MANAGER_DASHBOARD_FAIL = "CREATE_WAREHOUSE_MANAGER_DASHBOARD_FAIL";