export const CREATE_DEVICE_INSTALL_REQUEST = "CREATE_DEVICE_INSTALL_REQUEST";
export const CREATE_DEVICE_INSTALL_SUCCESS = "CREATE_DEVICE_INSTALL_SUCCESS";
export const CREATE_DEVICE_INSTALL_FAILURE = "CREATE_DEVICE_INSTALL_FAILURE";
export const UPLOAD_DEVICE_INSTALL_REQUEST = "UPLOAD_DEVICE_INSTALL_REQUEST";
export const UPLOAD_DEVICE_INSTALL_SUCCESS = "UPLOAD_DEVICE_INSTALL_SUCCESS";
export const UPLOAD_DEVICE_INSTALL_FAILURE = "UPLOAD_DEVICE_INSTALL_FAILURE";
export const UPDATE_DEVICE_INSTALL_REQUEST = "UPDATE_DEVICE_INSTALL_REQUEST";
export const DELETE_DEVICE_INSTALL_REQUEST = "DELETE_DEVICE_INSTALL_REQUEST";