export const FETCH_ESTIMATES_REQUEST = "FETCH_ESTIMATES_REQUEST";
export const FETCH_ESTIMATES_SUCCESS = "FETCH_ESTIMATES_SUCCESS";
export const FETCH_ESTIMATES_FAIL = "FETCH_ESTIMATES_FAIL";

export const FETCH_INVOICES_REQUEST = "FETCH_INVOICES_REQUEST";
export const FETCH_INVOICES_SUCCESS = "FETCH_INVOICES_SUCCESS";
export const FETCH_INVOICES_FAIL = "FETCH_INVOICES_FAIL";

export const FETCH_RECIEPTS_REQUEST = "FETCH_RECIEPTS_REQUEST";
export const FETCH_RECIEPTS_SUCCESS = "FETCH_RECIEPTS_SUCCESS";
export const FETCH_RECIEPTS_FAIL = "FETCH_RECIEPTS_FAIL";

export const ESTIMATE_DETAIL_REQUEST = "ESTIMATE_DETAIL_REQUEST";
export const ESTIMATE_DETAIL_SUCCESS = "ESTIMATE_DETAIL_SUCCESS";
export const ESTIMATE_DETAIL_FAIL = "ESTIMATE_DETAIL_FAIL";

export const RECIEPT_DETAIL_REQUEST = "RECIEPT_DETAIL_REQUEST";
export const RECIEPT_DETAIL_SUCCESS = "RECIEPT_DETAIL_SUCCESS";
export const RECIEPT_DETAIL_FAIL = "RECIEPT_DETAIL_FAIL";

export const INVOICE_DETAIL_REQUEST = "INVOICE_DETAIL_REQUEST";
export const INVOICE_DETAIL_SUCCESS = "INVOICE_DETAIL_SUCCESS";
export const INVOICE_DETAIL_FAIL = "INVOICE_DETAIL_FAIL";

export const CREATE_ESTIMATE_REQUEST = "CREATE_ESTIMATE_REQUEST";
export const CREATE_ESTIMATE_SUCCESS = "CREATE_ESTIMATE_SUCCESS";
export const CREATE_ESTIMATE_FAIL = "CREATE_ESTIMATE_FAIL";

export const CREATE_INVOICE_REQUEST = "CREATE_INVOICE_REQUEST";
export const CREATE_INVOICE_SUCCESS = "CREATE_INVOICE_SUCCESS";
export const CREATE_INVOICE_FAIL = "CREATE_INVOICE_FAIL";

export const CREATE_RECIEPT_REQUEST = "CREATE_RECIEPT_REQUEST";
export const CREATE_RECIEPT_SUCCESS = "CREATE_RECIEPT_SUCCESS";
export const CREATE_RECIEPT_FAIL = "CREATE_RECIEPT_FAIL";

export const UPDATE_ESTIMATE_REQUEST = "UPDATE_ESTIMATE_REQUEST";
export const UPDATE_ESTIMATE_SUCCESS = "UPDATE_ESTIMATE_SUCCESS";
export const UPDATE_ESTIMATE_FAIL = "UPDATE_ESTIMATE_FAIL";

export const DELETE_ESTIMATE_REQUEST = "DELETE_ESTIMATE_REQUEST";
export const DELETE_ESTIMATE_SUCCESS = "DELETE_ESTIMATE_SUCCESS";
export const DELETE_ESTIMATE_FAIL = "DELETE_ESTIMATE_FAIL";