export const FETCH_HIRINGS_REQUEST = "FETCH_HIRINGS_REQUEST";
export const FETCH_HIRINGS_SUCCESS = "FETCH_HIRINGS_SUCCESS";
export const FETCH_HIRINGS_FAIL = "FETCH_HIRINGS_FAIL";

export const HIRING_DETAIL_REQUEST = "HIRING_DETAIL_REQUEST";
export const HIRING_DETAIL_SUCCESS = "HIRING_DETAIL_SUCCESS";
export const HIRING_DETAIL_FAIL = "HIRING_DETAIL_FAIL";

export const CREATE_HIRING_REQUEST = "CREATE_HIRING_REQUEST";
export const CREATE_HIRING_SUCCESS = "CREATE_HIRING_SUCCESS";
export const CREATE_HIRING_FAIL = "CREATE_HIRING_FAIL";

export const UPDATE_HIRING_REQUEST = "UPDATE_HIRING_REQUEST";
export const UPDATE_HIRING_SUCCESS = "UPDATE_HIRING_SUCCESS";
export const UPDATE_HIRING_FAIL = "UPDATE_HIRING_FAIL";

export const DELETE_HIRING_REQUEST = "DELETE_HIRING_REQUEST";
export const DELETE_HIRING_SUCCESS = "DELETE_HIRING_SUCCESS";
export const DELETE_HIRING_FAIL = "DELETE_HIRING_FAIL";