
export const GET_NOTIFICATIONS_REQUEST = "GET_NOTIFICATIONS_REQUEST";
export const GET_NOTIFICATIONS_SUCCESS = "GET_NOTIFICATIONS_SUCCESS";
export const GET_NOTIFICATIONS_FAIL = "GET_NOTIFICATIONS_FAIL";

export const CREATE_NOTIFICATION_REQUEST = "CREATE_NOTIFICATION_REQUEST";
export const CREATE_NOTIFICATION_SUCCESS = "CREATE_NOTIFICATION_SUCCESS";
export const CREATE_NOTIFICATION_FAIL = "CREATE_NOTIFICATION_FAIL";

export const NOTIFICATION_DETAIL_REQUEST = "NOTIFICATION_DETAIL_REQUEST";
export const NOTIFICATION_DETAIL_SUCCESS = "NOTIFICATION_DETAIL_SUCCESS";
export const NOTIFICATION_DETAIL_FAIL = "NOTIFICATION_DETAIL_FAIL";

