export const FETCH_PRODUCT_ASSIGNS_REQUEST = "FETCH_PRODUCT_ASSIGNS_REQUEST";
export const FETCH_PRODUCT_ASSIGNS_SUCCESS = "FETCH_PRODUCT_ASSIGNS_SUCCESS";
export const FETCH_PRODUCT_ASSIGNS_FAIL = "FETCH_PRODUCT_ASSIGNS_FAIL";

export const PRODUCT_ASSIGN_DETAIL_REQUEST = "PRODUCT_ASSIGN_DETAIL_REQUEST";
export const PRODUCT_ASSIGN_DETAIL_SUCCESS = "PRODUCT_ASSIGN_DETAIL_SUCCESS";
export const PRODUCT_ASSIGN_DETAIL_FAIL = "PRODUCT_ASSIGN_DETAIL_FAIL";

export const CREATE_PRODUCT_ASSIGN_REQUEST = "CREATE_PRODUCT_ASSIGN_REQUEST";
export const CREATE_PRODUCT_ASSIGN_SUCCESS = "CREATE_PRODUCT_ASSIGN_SUCCESS";
export const CREATE_PRODUCT_ASSIGN_FAIL = "CREATE_PRODUCT_ASSIGN_FAIL";

export const UPDATE_PRODUCT_ASSIGN_REQUEST = "UPDATE_PRODUCT_ASSIGN_REQUEST";
export const UPDATE_PRODUCT_ASSIGN_SUCCESS = "UPDATE_PRODUCT_ASSIGN_SUCCESS";
export const UPDATE_PRODUCT_ASSIGN_FAIL = "UPDATE_PRODUCT_ASSIGN_FAIL";

export const DELETE_PRODUCT_ASSIGN_REQUEST = "DELETE_PRODUCT_ASSIGN_REQUEST";
export const DELETE_PRODUCT_ASSIGN_SUCCESS = "DELETE_PRODUCT_ASSIGN_SUCCESS";
export const DELETE_PRODUCT_ASSIGN_FAIL = "DELETE_PRODUCT_ASSIGN_FAIL";