export const FETCH_RAISE_REQUESTS_REQUEST = "FETCH_RAISE_REQUESTS_REQUEST";
export const FETCH_RAISE_REQUESTS_SUCCESS = "FETCH_RAISE_REQUESTS_SUCCESS";
export const FETCH_RAISE_REQUESTS_FAIL = "FETCH_RAISE_REQUESTS_FAIL";

export const RAISE_REQUEST_DETAIL_REQUEST = "RAISE_REQUEST_DETAIL_REQUEST";
export const RAISE_REQUEST_DETAIL_SUCCESS = "RAISE_REQUEST_DETAIL_SUCCESS";
export const RAISE_REQUEST_DETAIL_FAIL = "RAISE_REQUEST_DETAIL_FAIL";

export const CREATE_RAISE_REQUEST_REQUEST = "CREATE_RAISE_REQUEST_REQUEST";
export const CREATE_RAISE_REQUEST_SUCCESS = "CREATE_RAISE_REQUEST_SUCCESS";
export const CREATE_RAISE_REQUEST_FAIL = "CREATE_RAISE_REQUEST_FAIL";

export const UPDATE_RAISE_REQUEST_REQUEST = "UPDATE_RAISE_REQUEST_REQUEST";
export const UPDATE_RAISE_REQUEST_SUCCESS = "UPDATE_RAISE_REQUEST_SUCCESS";
export const UPDATE_RAISE_REQUEST_FAIL = "UPDATE_RAISE_REQUEST_FAIL";

export const DELETE_RAISE_REQUEST_REQUEST = "DELETE_RAISE_REQUEST_REQUEST";
export const DELETE_RAISE_REQUEST_SUCCESS = "DELETE_RAISE_REQUEST_SUCCESS";
export const DELETE_RAISE_REQUEST_FAIL = "DELETE_RAISE_REQUEST_FAIL";