export const CREATE_SALES_VISIT_REQUEST = "CREATE_SALES_VISIT_REQUEST";
export const CREATE_SALES_VISIT_SUCCESS = "CREATE_SALES_VISIT_SUCCESS";
export const CREATE_SALES_VISIT_FAILURE = "CREATE_SALES_VISIT_FAILURE";
export const UPLOADE_SALES_VISIT_REQUEST = "UPLOADE_SALES_VISIT_REQUEST";
export const UPLOADE_SALES_VISIT_SUCCESS = "UPLOADE_SALES_VISIT_SUCCESS";
export const UPLOADE_SALES_VISIT_FAILURE = "UPLOADE_SALES_VISIT_FAILURE";
export const UPDATE_SALES_VISIT_REQUEST = "UPDATE_SALES_VISIT_REQUEST";
export const DELETE_SALES_VISIT_REQUEST = "DELETE_SALES_VISIT_REQUEST";