export const CREATE_SALES_VISIT_REQUEST = "CREATE_SALES_VISIT_REQUEST";
export const CREATE_SALES_VISIT_SUCCESS = "CREATE_SALES_VISIT_SUCCESS";
export const CREATE_SALES_VISIT_FAILURE = "CREATE_SALES_VISIT_FAILURE";
export const UPLOAD_SALES_VISIT_REQUEST = "UPLOAD_SALES_VISIT_REQUEST";
export const UPLOAD_SALES_VISIT_SUCCESS = "UPLOAD_SALES_VISIT_SUCCESS";
export const UPLOAD_SALES_VISIT_FAILURE = "UPLOAD_SALES_VISIT_FAILURE";
export const UPDATE_SALES_VISIT_REQUEST = "UPDATE_SALES_VISIT_REQUEST";
export const DELETE_SALES_VISIT_REQUEST = "DELETE_SALES_VISIT_REQUEST";