export const FETCH_STAFFS_REQUEST = "FETCH_STAFFS_REQUEST";
export const FETCH_STAFFS_SUCCESS = "FETCH_STAFFS_SUCCESS";
export const FETCH_STAFFS_FAIL = "FETCH_STAFFS_FAIL";

export const FETCH_STAFF_PERMISSION_REQUEST = "FETCH_STAFF_PERMISSION_REQUEST";
export const FETCH_STAFF_PERMISSION_SUCCESS = "FETCH_STAFF_PERMISSION_SUCCESS";
export const FETCH_STAFF_PERMISSION_FAIL = "FETCH_STAFF_PERMISSION_FAIL";

export const UPDATE_STAFF_PERMISSION_REQUEST = "UPDATE_STAFF_PERMISSION_REQUEST";
export const UPDATE_STAFF_PERMISSION_SUCCESS = "UPDATE_STAFF_PERMISSION_SUCCESS";
export const UPDATE_STAFF_PERMISSION_FAIL = "UPDATE_STAFF_PERMISSION_FAIL";

export const FETCH_STAFFS_DROPDOWN_REQUEST = "FETCH_STAFFS_DROPDOWN_REQUEST";
export const FETCH_STAFFS_DROPDOWN_SUCCESS = "FETCH_STAFFS_DROPDOWN_SUCCESS";
export const FETCH_STAFFS_DROPDOWN_FAIL = "FETCH_STAFFS_DROPDOWN_FAIL";

export const STAFF_DETAIL_REQUEST = "STAFF_DETAIL_REQUEST";
export const STAFF_DETAIL_SUCCESS = "STAFF_DETAIL_SUCCESS";
export const STAFF_DETAIL_FAIL = "STAFF_DETAIL_FAIL";

export const CREATE_STAFF_REQUEST = "CREATE_STAFF_REQUEST";
export const CREATE_STAFF_SUCCESS = "CREATE_STAFF_SUCCESS";
export const CREATE_STAFF_FAIL = "CREATE_STAFF_FAIL";

export const UPDATE_STAFF_REQUEST = "UPDATE_STAFF_REQUEST";
export const UPDATE_STAFF_SUCCESS = "UPDATE_STAFF_SUCCESS";
export const UPDATE_STAFF_FAIL = "UPDATE_STAFF_FAIL";

export const SEARCH_STAFF_REQUEST = "SEARCH_STAFF_REQUEST";
export const SEARCH_STAFF_SUCCESS = "SEARCH_STAFF_SUCCESS";
export const SEARCH_STAFF_FAIL = "SEARCH_STAFF_FAIL";

export const DELETE_STAFF_REQUEST = "DELETE_STAFF_REQUEST";
export const DELETE_STAFF_SUCCESS = "DELETE_STAFF_SUCCESS";
export const DELETE_STAFF_FAIL = "DELETE_STAFF_FAIL";