export const FETCH_SUBDEALERS_REQUEST = "FETCH_SUBDEALERS_REQUEST";
export const FETCH_SUBDEALERS_SUCCESS = "FETCH_SUBDEALERS_SUCCESS";
export const FETCH_SUBDEALERS_FAIL = "FETCH_SUBDEALERS_FAIL";

export const FETCH_SUBDEALERS_DROPDOWN_REQUEST = "FETCH_SUBDEALERS_DROPDOWN_REQUEST";
export const FETCH_SUBDEALERS_DROPDOWN_SUCCESS = "FETCH_SUBDEALERS_DROPDOWN_SUCCESS";
export const FETCH_SUBDEALERS_DROPDOWN_FAIL = "FETCH_SUBDEALERS_DROPDOWN_FAIL";

export const SUBDEALER_DETAIL_REQUEST = "SUBDEALER_DETAIL_REQUEST";
export const SUBDEALER_DETAIL_SUCCESS = "SUBDEALER_DETAIL_SUCCESS";
export const SUBDEALER_DETAIL_FAIL = "SUBDEALER_DETAIL_FAIL";

export const CREATE_SUBDEALER_REQUEST = "CREATE_SUBDEALER_REQUEST";
export const CREATE_SUBDEALER_SUCCESS = "CREATE_SUBDEALER_SUCCESS";
export const CREATE_SUBDEALER_FAIL = "CREATE_SUBDEALER_FAIL";

export const UPDATE_SUBDEALER_REQUEST = "UPDATE_SUBDEALER_REQUEST";
export const UPDATE_SUBDEALER_SUCCESS = "UPDATE_SUBDEALER_SUCCESS";
export const UPDATE_SUBDEALER_FAIL = "UPDATE_SUBDEALER_FAIL";

export const DELETE_SUBDEALER_REQUEST = "DELETE_SUBDEALER_REQUEST";
export const DELETE_SUBDEALER_SUCCESS = "DELETE_SUBDEALER_SUCCESS";
export const DELETE_SUBDEALER_FAIL = "DELETE_SUBDEALER_FAIL";