export const FETCH_TECH_WORKS_REQUEST = "FETCH_TECH_WORKS_REQUEST";
export const FETCH_TECH_WORKS_SUCCESS = "FETCH_TECH_WORKS_SUCCESS";
export const FETCH_TECH_WORKS_FAIL = "FETCH_TECH_WORKS_FAIL";

export const TECH_WORK_DETAIL_REQUEST = "TECH_WORK_DETAIL_REQUEST";
export const TECH_WORK_DETAIL_SUCCESS = "TECH_WORK_DETAIL_SUCCESS";
export const TECH_WORK_DETAIL_FAIL = "TECH_WORK_DETAIL_FAIL";

export const CREATE_TECH_WORK_REQUEST = "CREATE_TECH_WORK_REQUEST";
export const CREATE_TECH_WORK_SUCCESS = "CREATE_TECH_WORK_SUCCESS";
export const CREATE_TECH_WORK_FAIL = "CREATE_TECH_WORK_FAIL";

export const UPDATE_TECH_WORK_REQUEST = "UPDATE_TECH_WORK_REQUEST";
export const UPDATE_TECH_WORK_SUCCESS = "UPDATE_TECH_WORK_SUCCESS";
export const UPDATE_TECH_WORK_FAIL = "UPDATE_TECH_WORK_FAIL";

export const DELETE_TECH_WORK_REQUEST = "DELETE_TECH_WORK_REQUEST";
export const DELETE_TECH_WORK_SUCCESS = "DELETE_TECH_WORK_SUCCESS";
export const DELETE_TECH_WORK_FAIL = "DELETE_TECH_WORK_FAIL";