export const FETCH_TICKETS_REQUEST = "FETCH_TICKETS_REQUEST";
export const FETCH_TICKETS_SUCCESS = "FETCH_TICKETS_SUCCESS";
export const FETCH_TICKETS_FAIL = "FETCH_TICKETS_FAIL";

export const TICKET_DETAIL_REQUEST = "TICKET_DETAIL_REQUEST";
export const TICKET_DETAIL_SUCCESS = "TICKET_DETAIL_SUCCESS";
export const TICKET_DETAIL_FAIL = "TICKET_DETAIL_FAIL";

export const TICKET_PRODUCT_REQUEST = "TICKET_PRODUCT_REQUEST";
export const TICKET_PRODUCT_SUCCESS = "TICKET_PRODUCT_SUCCESS";
export const TICKET_PRODUCT_FAIL = "TICKET_PRODUCT_FAIL";

export const CREATE_TICKET_REQUEST = "CREATE_TICKET_REQUEST";
export const CREATE_TICKET_SUCCESS = "CREATE_TICKET_SUCCESS";
export const CREATE_TICKET_FAIL = "CREATE_TICKET_FAIL";

export const UPDATE_TICKET_REQUEST = "UPDATE_TICKET_REQUEST";
export const UPDATE_TICKET_SUCCESS = "UPDATE_TICKET_SUCCESS";
export const UPDATE_TICKET_FAIL = "UPDATE_TICKET_FAIL";

export const DELETE_TICKET_REQUEST = "DELETE_TICKET_REQUEST";
export const DELETE_TICKET_SUCCESS = "DELETE_TICKET_SUCCESS";
export const DELETE_TICKET_FAIL = "DELETE_TICKET_FAIL";