export const FETCH_VENDORS_REQUEST = "FETCH_VENDORS_REQUEST";
export const FETCH_VENDORS_SUCCESS = "FETCH_VENDORS_SUCCESS";
export const FETCH_VENDORS_FAIL = "FETCH_VENDORS_FAIL";

export const FETCH_VENDORS_DROPDOWN_REQUEST = "FETCH_VENDORS_DROPDOWN_REQUEST";
export const FETCH_VENDORS_DROPDOWN_SUCCESS = "FETCH_VENDORS_DROPDOWN_SUCCESS";
export const FETCH_VENDORS_DROPDOWN_FAIL = "FETCH_VENDORS_DROPDOWN_FAIL";

export const VENDOR_DETAIL_REQUEST = "VENDOR_DETAIL_REQUEST";
export const VENDOR_DETAIL_SUCCESS = "VENDOR_DETAIL_SUCCESS";
export const VENDOR_DETAIL_FAIL = "VENDOR_DETAIL_FAIL";

export const CREATE_VENDOR_REQUEST = "CREATE_VENDOR_REQUEST";
export const CREATE_VENDOR_SUCCESS = "CREATE_VENDOR_SUCCESS";
export const CREATE_VENDOR_FAIL = "CREATE_VENDOR_FAIL";

export const UPDATE_VENDOR_REQUEST = "UPDATE_VENDOR_REQUEST";
export const UPDATE_VENDOR_SUCCESS = "UPDATE_VENDOR_SUCCESS";
export const UPDATE_VENDOR_FAIL = "UPDATE_VENDOR_FAIL";

export const DELETE_VENDOR_REQUEST = "DELETE_VENDOR_REQUEST";
export const DELETE_VENDOR_SUCCESS = "DELETE_VENDOR_SUCCESS";
export const DELETE_VENDOR_FAIL = "DELETE_VENDOR_FAIL";