export const FETCH_VOUCHERS_REQUEST = "FETCH_VOUCHERS_REQUEST";
export const FETCH_VOUCHERS_SUCCESS = "FETCH_VOUCHERS_SUCCESS";
export const FETCH_VOUCHERS_FAIL = "FETCH_VOUCHERS_FAIL";

export const FETCH_VOUCHER_PAYMENTS_REQUEST = "FETCH_VOUCHER_PAYMENTS_REQUEST";
export const FETCH_VOUCHER_PAYMENTS_SUCCESS = "FETCH_VOUCHER_PAYMENTS_SUCCESS";
export const FETCH_VOUCHER_PAYMENTS_FAIL = "FETCH_VOUCHER_PAYMENTS_FAIL";

export const FETCH_VOUCHER_RECIEPTS_REQUEST = "FETCH_VOUCHER_RECIEPTS_REQUEST";
export const FETCH_VOUCHER_RECIEPTS_SUCCESS = "FETCH_VOUCHER_RECIEPTS_SUCCESS";
export const FETCH_VOUCHER_RECIEPTS_FAIL = "FETCH_VOUCHER_RECIEPTS_FAIL";

export const FETCH_VOUCHER_PURCHASES_REQUEST = "FETCH_VOUCHER_PURCHASES_REQUEST";
export const FETCH_VOUCHER_PURCHASES_SUCCESS = "FETCH_VOUCHER_PURCHASES_SUCCESS";
export const FETCH_VOUCHER_PURCHASES_FAIL = "FETCH_VOUCHER_PURCHASES_FAIL";

export const FETCH_VOUCHER_LEDGERS_REQUEST = "FETCH_VOUCHER_LEDGERS_REQUEST";
export const FETCH_VOUCHER_LEDGERS_SUCCESS = "FETCH_VOUCHER_LEDGERS_SUCCESS";
export const FETCH_VOUCHER_LEDGERS_FAIL = "FETCH_VOUCHER_LEDGERS_FAIL";

export const FETCH_VOUCHER_DAYBOOK_REQUEST = "FETCH_VOUCHER_DAYBOOK_REQUEST";
export const FETCH_VOUCHER_DAYBOOK_SUCCESS = "FETCH_VOUCHER_DAYBOOK_SUCCESS";
export const FETCH_VOUCHER_DAYBOOK_FAIL = "FETCH_VOUCHER_DAYBOOK_FAIL";

export const VOUCHER_DETAIL_REQUEST = "VOUCHER_DETAIL_REQUEST";
export const VOUCHER_DETAIL_SUCCESS = "VOUCHER_DETAIL_SUCCESS";
export const VOUCHER_DETAIL_FAIL = "VOUCHER_DETAIL_FAIL";

export const CREATE_VOUCHER_REQUEST = "CREATE_VOUCHER_REQUEST";
export const CREATE_VOUCHER_SUCCESS = "CREATE_VOUCHER_SUCCESS";
export const CREATE_VOUCHER_FAIL = "CREATE_VOUCHER_FAIL";

export const UPDATE_VOUCHER_REQUEST = "UPDATE_VOUCHER_REQUEST";
export const UPDATE_VOUCHER_SUCCESS = "UPDATE_VOUCHER_SUCCESS";
export const UPDATE_VOUCHER_FAIL = "UPDATE_VOUCHER_FAIL";

export const DELETE_VOUCHER_REQUEST = "DELETE_VOUCHER_REQUEST";
export const DELETE_VOUCHER_SUCCESS = "DELETE_VOUCHER_SUCCESS";
export const DELETE_VOUCHER_FAIL = "DELETE_VOUCHER_FAIL";
