export const FETCH_WORK_ALLOCATIONS_REQUEST = "FETCH_WORK_ALLOCATIONS_REQUEST";
export const FETCH_WORK_ALLOCATIONS_SUCCESS = "FETCH_WORK_ALLOCATIONS_SUCCESS";
export const FETCH_WORK_ALLOCATIONS_FAIL = "FETCH_WORK_ALLOCATIONS_FAIL";

export const WORK_ALLOCATION_DETAIL_REQUEST = "WORK_ALLOCATION_DETAIL_REQUEST";
export const WORK_ALLOCATION_DETAIL_SUCCESS = "WORK_ALLOCATION_DETAIL_SUCCESS";
export const WORK_ALLOCATION_DETAIL_FAIL = "WORK_ALLOCATION_DETAIL_FAIL";

export const CREATE_WORK_ALLOCATION_REQUEST = "CREATE_WORK_ALLOCATION_REQUEST";
export const CREATE_WORK_ALLOCATION_SUCCESS = "CREATE_WORK_ALLOCATION_SUCCESS";
export const CREATE_WORK_ALLOCATION_FAIL = "CREATE_WORK_ALLOCATION_FAIL";

export const UPDATE_WORK_ALLOCATION_REQUEST = "UPDATE_WORK_ALLOCATION_REQUEST";
export const UPDATE_WORK_ALLOCATION_SUCCESS = "UPDATE_WORK_ALLOCATION_SUCCESS";
export const UPDATE_WORK_ALLOCATION_FAIL = "UPDATE_WORK_ALLOCATION_FAIL";

export const DELETE_WORK_ALLOCATION_REQUEST = "DELETE_WORK_ALLOCATION_REQUEST";
export const DELETE_WORK_ALLOCATION_SUCCESS = "DELETE_WORK_ALLOCATION_SUCCESS";
export const DELETE_WORK_ALLOCATION_FAIL = "DELETE_WORK_ALLOCATION_FAIL";